language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install --upgrade pylint bandit black
# command to run tests
script:
  - black --check -t py38 src  #fail if is not correctly formated
  - pylint -f colorized --disable=R,C,W  src/
  - bandit -r . -n 3 -ll || true #do not mark the build as failed
